const demoPosts = [
  {
    id: 1,
    author: {
      name: "Somoy News TV",
      username: "somoynews.tv",
      verified: true,
      avatar: "https://i.pravatar.cc/150?img=11",
    },
    time: "2h",
    privacy: "public",
    content:
      "আমি আমার দাদাকে কখনো দেখিনি। কিন্তু তাঁর সততা আর দেশপ্রেমের কথা দাদু আসে শুনে সেই চলেছি।",
    quoteAuthor: "জাহিদ হাসান",
    category: "সময়",
    likes: 3700,
    comments: 289,
    shares: 30,
  },
  {
    id: 2,
    author: {
      name: "Daily Update",
      username: "daily.update",
      verified: false,
      avatar: "https://i.pravatar.cc/150?img=12",
    },
    time: "4h",
    privacy: "public",
    content: "পরিশ্রম কখনো বৃথা যায় না। সময় নেয়, কিন্তু ফল অবশ্যই আসে।",
    quoteAuthor: "অজানা",
    category: "অনুপ্রেরণা",
    likes: 2100,
    comments: 145,
    shares: 18,
  },
  {
    id: 3,
    author: {
      name: "Bangla Quotes",
      username: "bangla.quotes",
      verified: true,
      avatar: "https://i.pravatar.cc/150?img=13",
    },
    time: "6h",
    privacy: "public",
    content: "নিজেকে বদলাতে পারলে দুনিয়াকে বদলানো সহজ হয়ে যায়।",
    quoteAuthor: "ইমাম গাজ্জালি (রহ.)",
    category: "ইসলামিক",
    likes: 5400,
    comments: 412,
    shares: 76,
  },
  {
    id: 4,
    author: {
      name: "Life Lessons",
      username: "life.lessons",
      verified: false,
      avatar: "https://i.pravatar.cc/150?img=14",
    },
    time: "8h",
    privacy: "public",
    content: "ভুল থেকে শেখাই হলো জীবনের সবচেয়ে বড় শিক্ষা।",
    quoteAuthor: "অজানা",
    category: "জীবন",
    likes: 1800,
    comments: 96,
    shares: 12,
  },
  {
    id: 5,
    author: {
      name: "Tech Bangla",
      username: "tech.bangla",
      verified: true,
      avatar: "https://i.pravatar.cc/150?img=15",
    },
    time: "10h",
    privacy: "public",
    content: "টেকনোলজি তখনই কাজে আসে, যখন তা মানুষের সমস্যা সমাধান করে।",
    quoteAuthor: "টেক কমিউনিটি",
    category: "টেক",
    likes: 3200,
    comments: 210,
    shares: 44,
  },
  {
    id: 6,
    author: {
      name: "Islamic Reminder",
      username: "islamic.reminder",
      verified: true,
      avatar: "https://i.pravatar.cc/150?img=16",
    },
    time: "12h",
    privacy: "public",
    content: "ধৈর্য ধারণ করো, নিশ্চয়ই আল্লাহ ধৈর্যশীলদের সঙ্গে আছেন।",
    quoteAuthor: "কুরআন",
    category: "ইসলামিক",
    likes: 6100,
    comments: 530,
    shares: 120,
  },
  {
    id: 7,
    author: {
      name: "Student Life",
      username: "student.life",
      verified: false,
      avatar: "https://i.pravatar.cc/150?img=17",
    },
    time: "14h",
    privacy: "public",
    content: "আজকের কষ্টই আগামী দিনের শক্তি।",
    quoteAuthor: "একজন শিক্ষার্থী",
    category: "মোটিভেশন",
    likes: 2500,
    comments: 167,
    shares: 29,
  },
  {
    id: 8,
    author: {
      name: "Positive Mind",
      username: "positive.mind",
      verified: false,
      avatar: "https://i.pravatar.cc/150?img=18",
    },
    time: "16h",
    privacy: "public",
    content: "সবকিছু ঠিক হয়ে যাবে—এই বিশ্বাসটাই আমাদের সামনে এগিয়ে নেয়।",
    quoteAuthor: "অজানা",
    category: "পজিটিভ",
    likes: 1900,
    comments: 88,
    shares: 15,
  },
  {
    id: 9,
    author: {
      name: "Career Talk",
      username: "career.talk",
      verified: true,
      avatar: "https://i.pravatar.cc/150?img=19",
    },
    time: "18h",
    privacy: "public",
    content: "দক্ষতা বাড়াও, সুযোগ নিজেই তোমাকে খুঁজে নেবে।",
    quoteAuthor: "ক্যারিয়ার কোচ",
    category: "ক্যারিয়ার",
    likes: 4100,
    comments: 305,
    shares: 61,
  },
  {
    id: 10,
    author: {
      name: "Bangladesh Today",
      username: "bd.today",
      verified: true,
      avatar: "https://i.pravatar.cc/150?img=20",
    },
    time: "1d",
    privacy: "public",
    content: "দেশকে ভালোবাসা মানে শুধু কথা নয়, কাজেও তা প্রমাণ করা।",
    quoteAuthor: "অজানা",
    category: "দেশ",
    likes: 7200,
    comments: 680,
    shares: 150,
  },
];

export const postData = {
  demoPosts,
};
